upstream:
  url: https://demo.promlabs.com
  # url: https://ng-api-http.eu2.coralogix.com/metrics
  include_query_stats: true

database:
  provider: clickhouse
  clickhouse:
    auth:
      database: default
  sqlite:
    database_path: ./prom-analytics-proxy.db
# tracing:
#   client_type: "grpc"
#   service_name: "prom-analytics-proxy"
#   endpoint: "localhost:4317"
#   insecure: true
#   sampler_type: "alwayssample"
